server:
  port: 8081
application:
  name: experian-route
spring:
  cloud:
    gateway:
      routes:
      - id: experian_route
        uri: http://localhost:8085
        predicates:
        - Path=/experian/**
      - id: credit-status
        uri: http://localhost:8080
        predicates:
        - Path=/credit-status/**
